# Generated by Django 2.2.3 on 2019-07-19 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sbu_id', models.IntegerField()),
                ('location', models.CharField(max_length=30)),
                ('ticket_type', models.CharField(max_length=10)),
                ('details', models.CharField(max_length=100)),
                ('time_stamp', models.DateTimeField(verbose_name='date submitted')),
                ('ticket_assigned', models.BooleanField(default=False)),
                ('ticket_assigned_to', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('tickets_assigned', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketing_system.Ticket')),
            ],
        ),
    ]
