# Generated by Django 2.2.3 on 2019-07-29 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketing_system', '0003_auto_20190720_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_assigned_to',
            field=models.CharField(default='admin', max_length=20),
        ),
    ]
